server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
    encoding:
      charset: UTF-8
      enabled: true
      force: true
security:
  user:
    name: anjuxing
    password: anjuxingeureka